import Head from 'next/head'
import Image from 'next/image'

import { getAllProducts } from '@/data/api'


type Props = {
  products: Product[]
}

export default function Home({ products }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        products.map((product) => (
          <div key={product.id}>
            <h1>{product.title}</h1>
            <p>{product.description}</p>
            <p>{product.price}</p>
          </div>
        ))
      }
    </>
  )
}

export async function getStaticProps() { 
  let products = []
  try {
    products = await getAllProducts()
  } catch (error) {
    /* handle error */
    return {
      notFound: true,
    }
  }

  if (!products) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      products,
    },
  }
}