import Head from 'next/head'
import { ProductCard } from '@/components/molecules/PruductCard'

import { getAllProducts } from '@/data/api'

import {
  Box,
  Grid,
  Typography,
} from '@mui/material'

type Props = {
  products: Product[]
}


const MapProductsToCards = ({ products }: Props) => { 
  return (
    <>
      {
        products.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))
      }
    </>
  )
}

export default function Home({ products }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: {
            xs: 'flex',
            md: 'grid',
          },
          gridTemplateColumns: 'repeat(3, 1fr)',
          placeItems: 'center',
          flexDirection: 'column',
          minHeight: '100vh',
          width: '100%',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '2rem',
          marginTop: '1rem',
          marginBottom: '1rem',
        }}
      >

          <MapProductsToCards products={products} />
      </Box>
    </>
  )
}

export async function getStaticProps() { 
  let products = []
  try {
    products = await getAllProducts()
  } catch (error) {
    /* handle error */
    return {
      notFound: true,
    }
  }

  if (!products) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      products,
    },
  }
}