import Head from 'next/head'
import { getAllProducts } from '@/data/api'
import { ProductCatalog } from '@/components/templates/Home'

type Props = {
  products: Product[]
}

export default function Home({ products }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductCatalog products={products} />
    </>
  )
}

export async function getStaticProps() { 
  let products = []
  try {
    products = await getAllProducts()
  } catch (error) {
    /* handle error */
    return {
      notFound: true,
    }
  }

  if (!products) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      products,
    },
  }
}